<a href="https://colab.research.google.com/github/mursalin49/Deep-Learning/blob/main/Activation_Functions_in_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install numpy

In [ ]:
import numpy as np

# 1. ReLU - Rectified Linear Unit (Hidden Layer)

In [2]:
def relu(x):
    return np.maximum(0, x)


In [ ]:
relu(10)

10

In [3]:
relu(-10)

NameError: name 'np' is not defined

In [ ]:
relu(np.array([-1, 0, 1, 2]))

array([0, 0, 1, 2])

# 2. Leaky ReLU (Hidden Layer)

Leaky ReLU allows a small, positive gradient when the unit is not active.

In [ ]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, x * alpha)


In [ ]:
leaky_relu(-1)

array(-0.01)

In [ ]:
leaky_relu(np.array([-1, 0, 1, 2]))

array([-0.01,  0.  ,  1.  ,  2.  ])

# 3. ELU - Exponential Linear Unit (Hidden Layer)

ELU has a small slope for negative values, unlike ReLU, to avoid the dying ReLU problem.

In [ ]:
def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

In [ ]:
elu(5)

array(5.)

In [ ]:
elu(np.array([-1, 0, 1, 2]))

array([-0.63212056,  0.        ,  1.        ,  2.        ])

# 4. Sigmoid (Output Layer & Binaryclass Problem)

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [ ]:
sigmoid(np.array([-1, 0, 1, 2]))

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

# 5. Softmax (Output Layer & Multiclass Problem)

Softmax converts a real vector to a vector of categorical probabilities.

In [ ]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)


In [ ]:
proba = softmax(np.array([-1, 0, 1, 2]))
proba

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [ ]:
sum(proba)

1.0

# 6. Swish (Hidden Layer)

Swish is a self-gated activation function.

In [ ]:
def swish(x, beta=1.0):
    return x * sigmoid(beta * x)


In [ ]:
swish(5)

4.966535745378576

In [ ]:
swish(np.array([-1, 0, 1, 2]))

array([-0.26894142,  0.        ,  0.73105858,  1.76159416])

# 7. Linear (Output Layer)

Linear or identity activation function returns the input directly.

In [ ]:
def linear(x):
    return x

In [ ]:
linear(10)

10

# 8. Tanh (Hyperbolic Tangent)

In [ ]:
def tanh(x):
    return np.tanh(x)

In [ ]:
tanh(10)

0.9999999958776927

In [ ]:
tanh([-1, 0, 1, 2])

array([-0.76159416,  0.        ,  0.76159416,  0.96402758])

In [ ]:
import math

In [ ]:
def tanh(x):
    result = (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))
    return result

In [ ]:
tanh(-1)

-0.7615941559557649